package Vista;

import Controlador.ControladorGestor;
import Controlador.VistaLoginGestor;
import Modelo.Exception.PolloException;
import Modelo.Gestor;


public class VistaEscritorioLoginGestor extends javax.swing.JFrame implements VistaLoginGestor {


    private final ControladorGestor controladorGestor;

    public VistaEscritorioLoginGestor() throws PolloException {
        initComponents();
        controladorGestor = new ControladorGestor(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLoginGestor = new javax.swing.JButton();
        textGestorPwd = new javax.swing.JPasswordField();
        textGestorUser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Gestor");

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        btnLoginGestor.setText("Ingresar");
        btnLoginGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnLoginGestorActionPerformed(evt);
                } catch (PolloException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textGestorUser)
                    .addComponent(textGestorPwd)
                    .addComponent(btnLoginGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textGestorUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textGestorPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnLoginGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginGestorActionPerformed(java.awt.event.ActionEvent evt) throws PolloException {//GEN-FIRST:event_btnLoginGestorActionPerformed
        try {
            Gestor gestorLogueado = loginGestor();
            if(gestorLogueado != null){
                VistaEscritorioProcesarPedidos vista = new VistaEscritorioProcesarPedidos();
                vista.setVisible(true);
            }
        } catch (PolloException e) {
            throw new PolloException(e.getMessage());
        }
    }//GEN-LAST:event_btnLoginGestorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginGestor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField textGestorPwd;
    private javax.swing.JTextField textGestorUser;
    // End of variables declaration//GEN-END:variables

    @Override
    public Gestor loginGestor() throws PolloException {
        try {
            return controladorGestor.loginGestor(textGestorUser.getText(), textGestorPwd.getText());
        } catch (PolloException e) {
            throw new PolloException(e.getMessage());
        }
    }

    @Override
    public void mostrarError(String mensaje) {

    }
}
